var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)};$jscomp.ASSUME_ES5=!1;
$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.FORCE_POLYFILL_PROMISE=!1;$jscomp.FORCE_POLYFILL_PROMISE_WHEN_NO_UNHANDLED_REJECTION=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){if(a==Array.prototype||a==Object.prototype)return a;a[d]=b.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var d=0;d<a.length;++d){var b=a[d];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,d){var b=$jscomp.propertyToPolyfillSymbol[d];if(null==b)return a[d];b=a[b];return void 0!==b?b:a[d]};$jscomp.polyfill=function(a,d,b,c){d&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,d,b,c):$jscomp.polyfillUnisolated(a,d,b,c))};
$jscomp.polyfillUnisolated=function(a,d,b,c){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];if(!(f in b))return;b=b[f]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})};
$jscomp.polyfillIsolated=function(a,d,b,c){var f=a.split(".");a=1===f.length;c=f[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<f.length-1;h++){var e=f[h];if(!(e in c))return;c=c[e]}f=f[f.length-1];b=$jscomp.IS_SYMBOL_NATIVE&&"es6"===b?c[f]:null;d=d(b);null!=d&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:d}):d!==b&&(void 0===$jscomp.propertyToPolyfillSymbol[f]&&(b=1E9*Math.random()>>>0,$jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?
$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+b+"$"+f),$jscomp.defineProperty(c,$jscomp.propertyToPolyfillSymbol[f],{configurable:!0,writable:!0,value:d})))};$jscomp.assign=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.assign?Object.assign:function(a,d){for(var b=1;b<arguments.length;b++){var c=arguments[b];if(c)for(var f in c)$jscomp.owns(c,f)&&(a[f]=c[f])}return a};$jscomp.polyfill("Object.assign",function(a){return a||$jscomp.assign},"es6","es3");var retry=0;
function waitLZFR(){if(5<retry)return console.log("lzfr is not avaiable"),!1;"undefined"!=typeof window.lzfr?(window.lzfr.getSubmitForm=function(a,d){for(var b={},c=aimktFormConstant.PropertyName,f=aimktFormConstant.CookieName,h=aimktFormConstant.Attribute,e=$jscomp.makeIterator(a.SubmissionProperties),g=e.next();!g.done;g=e.next())g=g.value,b[g.InputName]=g.ContactPropertyValue;(e=this.getUrlParameter(c.UtmSource))&&(b[c.UtmSource]=e);(e=this.getUrlParameter(c.UtmTerm))&&(b[c.UtmTerm]=e);(e=this.getUrlParameter(c.UtmMedium))&&
(b[c.UtmMedium]=e);(e=this.getUrlParameter(c.UtmContent))&&(b[c.UtmContent]=e);(e=this.getUrlParameter(c.UtmCampaign))&&(b[c.UtmCampaign]=e);(e=this.getUrlParameter(c.Gclid))&&(b[c.Gclid]=e);(e=this.getUrlParameter(c.Fbclid))&&(b[c.Fbclid]=e);(e=this.getUrlParameter(c.EmailId))&&(b[c.EmailId]=e);(e=this.getUrlParameter(c.WorkflowId))&&(b[c.WorkflowId]=e);(e=this.getUrlParameter(c.ContactId))&&(b[c.ContactId]=e);b=Object.assign({},b,{ProfileID:this.getCookie(f.UcapProfileID),TenantID:d.companyID});
c=this.STATISTIC+"/api/ucap/eventcollector";try{var m=document.querySelector(".lpage-ucap[lz-id]"),k=null===m?"":m.getAttribute(h.LzID);k||(k="");var l={destinationURL:window.parent.location.href,pagePath:window.parent.location.pathname,pageOrigin:window.parent.location.origin,pageName:window.parent.document.title,referringURL:document.referrer||window.parent.document.referrer,lpageId:k};var q=l.hasOwnProperty("lpageId")?l.lpageId:void 0,n,p;fetch(c,{method:"POST",headers:{Authorization:"Basic "+
btoa("karaf:karaf"),"Content-type":"text/plain; charset=utf-8","Access-Control-Allow-Origin":"*"},body:JSON.stringify({events:[{eventType:202,scope:2,source:{itemType:"landingPageId",properties:l,itemId:q},target:{itemType:"formId",itemId:d.formID,properties:{TargetName:d.name,OwnerID:d.OwnerID,FormKey:d.FormKey}},properties:b}],sessionId:this.getCookie(f.UcapSessionID)})}).then(dataLayer.push({event:"form-submission",mddk:"tu-van",sdt:null==(n=b)?void 0:n.phoneNumber,email:null==(p=b)?void 0:p.email}))}catch(r){console.error("aimarketing_error GET FORM - ",
r)}},console.log("lzfr modified")):(retry++,setTimeout(waitLZFR,1E3))}waitLZFR();
